<?php
$translate = $this->plugin('translate');
$searchType = $this->siteSetting('search_type', 'sitewide');
switch ($searchType) {
    case 'cross-site':
        $searchAction = $this->url('site/cross-site-search', ['action' => 'results'], true);
        break;
    case 'sitewide':
    default:
        $searchAction = $this->url('site/resource', ['controller' => 'index', 'action' => 'search'], true);
}
$searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));
?>

<form action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item','action' => 'browse'], true)); ?>" id="search-form" class="input-group">
    <input type="text" name="property[0][text]" class="input-group-field" value="<?php echo $searchValue; ?>" placeholder="<?php echo $translate('Search'); ?>">
    <input type="hidden" name="property[0][joiner]" value="and"/>
    <input type="hidden" name="property[0][property]" value=""/>
    <input type="hidden" name="property[0][type]" value="in"/>
    <div class="input-group-button">
        <button class="button" type="submit"><?php echo $translate('Search'); ?></button>
    </div>
</form>
